config/routes.rb
Rails.application.routes.draw do

  root 'robots#index'

  get '/requests', to: 'robots#requests', as: :send_requests
  get '/random_song', to: 'robots#random_song', as: :send_random_song


end

app/models/mention.rb
class Mention < ActiveRecord::Base

  validates :mention_id, presence: true, uniqueness: true
  validates :reply_to, :mentioned_user, presence: true

  scope :unreplied_mentions, -> { where(status: "unreplied") }

  # Saves a mention property if not yet existing in Mentions table
  # default status: unreplied
  def self.save_mention(mention)
    find_or_create_by(mention_id: mention.id) do |attr|
      attr.mention_id = mention.id
      attr.reply_to = mention.user.screen_name
      attr.mentioned_user = mention.user_mentions.last.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  def index
  end

  def requests
    Tweet.new.requests
    redirect_to root_path, flash: { success: "Requests has been sent." }
  end

  def random_song
    Tweet.new.random_song
    redirect_to root_path, flash: { success: "Random song has been posted." }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Twitter Bot
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'shared/messages', flash: flash
    = yield

app/views/robots/index.haml
%h1 Welcome to Spotifycaster

.button-actions
  = link_to "Tweet Requested Songs", send_requests_path, class: "btn"
  = link_to "Tweet Random Song", send_random_song_path, class: "btn"

.main
  .container
    %a.twitter-timeline{"data-widget-id" => "639496940288241665", href: "https://twitter.com/spotifycaster"}

:javascript
  ! function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
          p = /^http:/.test(d.location) ? 'http' : 'https';
      if (!d.getElementById(id)) {
          js = d.createElement(s);
          js.id = id;
          js.src = p + "://platform.twitter.com/widgets.js";
          fjs.parentNode.insertBefore(js, fjs);
      }
  }(document, "script", "twitter-wjs");

app/views/shared/_messages.haml
- flash.each do |type, message|
  :javascript
    $(function() {
      humane.log('#{message}', { timeout: 5000, clickToClose: true, addnCls: 'humane-jackedup-#{type} humane-message' })
    });